spring:
  config:
    activate:
      on-profile: dev
server:
  port: 9001
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8000
#spring:
#  profiles: dev
#  server:
#    port: 9000
#---
#spring:
#  profiles: test
#  server:
#    port: 8000
